modLoader="javafml"
loaderVersion="[52,)"
license="Custom license (on GitHub)"
[[mods]]
modId="deathrium_collection"
version="1.0.0"
displayName="Deathrium Collection"
authors="antthLuca"
description='''TODO: Write description'''

[[dependencies.deathrium_collection]]
    modId="forge"
    mandatory=true
    versionRange="[52,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.deathrium_collection]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"
